version: "3.9"
   
services:
  web:
    build: .
    command: nohup python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/documanager
    ports:
      - "8000:8000"
    #env_file:
    #  - ./.env.dev
