# Generated by Django 4.1.2 on 2022-10-05 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documanager.utils.system_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_s', models.CharField(max_length=120)),
                ('file_path_s', models.CharField(max_length=500)),
                ('file_name_s', models.CharField(max_length=250)),
                ('file_type_s', models.CharField(max_length=50)),
                ('url_s', models.CharField(max_length=500)),
                ('created_at_dt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at_dt', models.DateTimeField(blank=True, null=True)),
                ('file_uploaded_b', models.FileField(blank=True, null=True, upload_to=documanager.utils.system_storage.upload_path_handler)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_s', models.CharField(max_length=120)),
                ('comment_s', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)])),
                ('number_i', models.IntegerField(default=1)),
                ('file_name_s', models.CharField(default='', max_length=250)),
                ('file_type_s', models.CharField(default='', max_length=50)),
                ('local_full_path_s', models.CharField(default='', max_length=500)),
                ('created_at_dt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at_dt', models.DateTimeField(blank=True, null=True)),
                ('file_uploaded_b', models.FileField(blank=True, null=True, upload_to=documanager.utils.system_storage.upload_path_handler2)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documanager.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documanager.user'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('url_s',), name='unique_url'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('file_uploaded_b',), name='unique_document'),
        ),
    ]
