# Generated by Django 4.1.2 on 2022-10-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documanager', '0002_populate_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='revisions_i',
            field=models.IntegerField(default=0),
        ),
    ]
